(lang dune 3.17)

(name Day03)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day03)
 (synopsis "AOC Solution for day 03")
 (description "")
 (depends ocaml batteries angstrom))
