(lang dune 3.17)

(name Day02)

(generate_opam_files true)

(source
 (github cainytheslave/AOC2024))

(authors "John Wagner <info@techbra.in>")

(license LICENSE)

(package
 (name Day02)
 (synopsis "AOC Solution for day 02")
 (description "")
 (depends ocaml))
